[default.extend-words]
OT = "OT"
OTK = "OTK"
OTKs = "OTKs"
NAX = "NAX"
fo = "fo"
Ue = "Ue"

[default.extend-identifiers]
BA = "BA"
Ba = "Ba"
td = "td"

[files]
extend-exclude = ["tests/critique_data/**", "tests/fixtures/**"]
